definitions:
    Binotto:
        x-go-package: github.com/smallcase/go-be-template/pkg/binotto
info:
    title: Go Template BE API
    version: v1.0.0
paths:
    /pets:
        get:
            consumes:
                - application/json
            description: |-
                This will show all available pets by default.
                You can get the pets that are out of stock
            operationId: listPets
            parameters:
                - description: maximum numnber of results to return
                  format: int32
                  in: query
                  name: limit
                  type: integer
            produces:
                - application/json
            responses:
                "200":
                    description: Binotto
                    schema:
                        $ref: '#/definitions/Binotto'
            schemes:
                - http
                - https
            summary: Lists pets filtered by some parameters.
            tags:
                - pets
swagger: "2.0"
